### ISSUE TITLE
Language debate

### ISSUE THREAD

**Issue by simonmaris** [burglabs/xlab-docs#11]
Our initial goal was to make this an English language knowledge base, mainly because we don't have the time to maintain two or more languages and most of the tools, terms and discussions in our fields of interest are mainly in English anyway. 

However, the fantastic #4 by @robin-gdwl has me thinking, I really want to merge this. 

So the question maybe is less about how we could support multiple languages, the answer is right here: 
https://evilmartians.com/chronicles/easy-multi-language-multi-version-documentation-with-docsify-git-and-github-actions

We should ask our selves, whether we have the long term goal to at least translate everything to English at some point (some sort of single language feature completeness) and who would be responsible for this and at which stage. 

Thoughts and ideas welcome! @alexabruck @svenja-sd

**Comment by alexabruck** [comment]
I think it's unrealistic to do everything in EN + DE. Let's do everything in EN, and translate the section by @robin-gdwl into EN soon!

**Comment by alexabruck** [comment]
Another option would be to have a distinct "Courses in German" section in the sidebar

**Comment by robin-gdwl** [comment]
It's a difficult question, it depends on the goal for the site. I it is intended mainly for students at BURG I believe it could be okay to have some pages in German with a disclaimer. But as I understand it, the site should also be used as a broader knowledge base accessible by people outside of BURG in that case it may be frustrating to them if the language changes.
Having everything in two languages probably won't work or is highly vulnerable to the two version being different from one another which also leads to confusion.
I could translate the text of the session description, however i will keep giving the Fusion-courses in German so the video tutorials will probably stay German, mainly because there were students who dif not speak English well enough to follow technical tutorials in English.

I am not sure if I could find the time to add English subtitles to all 16 videos.

I think the Fusion Courses would be a good addition to the site and would also be a good, permanent home for students to access the videos if they want to watch them again in the future (it would also increase traffic to the burglabs.github.io - site ;) )
But I also understand if you want to keep the site as clean and straightforward as possible, without switching languages.

Long story short:
Translation to English would take a while because of the videos. The Fusion 360 sites either stay in German with a disclaimer or I could move them to my own site and the xlab-docs - page simply link to them.

**Comment by simonmaris** [comment]
Thanks for both your inputs, many very valid points. Also, translating the videos is certainly no option. 

Slightly off-topic to answer your question: The long term goal for this site is definitely to be able to outgrow BURG and also the _typical student level_, since we have a clear research focus at BurgLabs on the one hand and it might be interesting for other research institutions and universities to join a collaborative effort.

I agree we should not do multi-language, however I still think specific courses can be linked in German or any other language for that matter.. So, as a plan for this project: let's indeed create that courses section, most of the content from #4 can live there. In the future there will also be more general pages on Fusion 360, those will be in English and will probably be less "chronological" than a course anyway.
